# Generated by Django 3.2.11 on 2022-04-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('article_code', models.IntegerField(primary_key=True, serialize=False)),
                ('search_name', models.CharField(max_length=30)),
                ('article_review_cnt', models.IntegerField()),
                ('article_pure_review_cnt', models.IntegerField()),
                ('search_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('blog_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('data', models.DateField()),
                ('thumnail_name', models.CharField(max_length=30)),
                ('picture_cnt', models.IntegerField()),
                ('aricle_code', models.ForeignKey(db_column='aricle_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.articleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_advertise', models.TextField()),
                ('content_summary', models.TextField()),
                ('content_positive', models.TextField()),
                ('content_negative', models.TextField()),
                ('aricle_code', models.ForeignKey(db_column='aricle_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.articleinfo')),
                ('blog_code', models.ForeignKey(db_column='blog_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.reviewdata')),
            ],
        ),
    ]
