# Generated by Django 3.2.11 on 2022-04-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('article_code', models.IntegerField(primary_key=True, serialize=False)),
                ('search_name', models.CharField(max_length=30)),
                ('article_review_cnt', models.IntegerField()),
                ('article_pure_review_cnt', models.IntegerField()),
                ('search_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_code', models.CharField(max_length=30)),
                ('article_code', models.IntegerField()),
                ('check_advertise', models.TextField()),
                ('content_summary', models.TextField()),
                ('content_positive', models.TextField()),
                ('content_negative', models.TextField()),
            ],
        ),
    ]
