# Generated by Django 3.2.11 on 2022-04-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='review_link',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='BuyList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('buylink', models.TextField()),
                ('buycoin', models.IntegerField()),
                ('aricle_code', models.ForeignKey(db_column='aricle_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.articleinfo')),
            ],
        ),
    ]
