# Generated by Django 3.2.11 on 2022-04-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0002_auto_20220420_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buylist',
            old_name='aricle_code',
            new_name='article_code',
        ),
        migrations.RenameField(
            model_name='reviewanalysis',
            old_name='aricle_code',
            new_name='article_code',
        ),
        migrations.RenameField(
            model_name='reviewdata',
            old_name='aricle_code',
            new_name='article_code',
        ),
    ]
