# Generated by Django 3.2.11 on 2022-04-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0003_auto_20220420_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylist',
            name='article_code',
            field=models.ForeignKey(db_column='article_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.articleinfo'),
        ),
        migrations.AlterField(
            model_name='reviewanalysis',
            name='article_code',
            field=models.ForeignKey(db_column='article_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.articleinfo'),
        ),
        migrations.AlterField(
            model_name='reviewdata',
            name='article_code',
            field=models.ForeignKey(db_column='article_code', on_delete=django.db.models.deletion.CASCADE, to='analysisapp.articleinfo'),
        ),
    ]
