# Generated by Django 3.2.11 on 2022-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0004_auto_20220420_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buylist',
            old_name='buycoin',
            new_name='buy_coin',
        ),
        migrations.RenameField(
            model_name='buylist',
            old_name='buylink',
            new_name='buy_link',
        ),
        migrations.AddField(
            model_name='buylist',
            name='buy_pla',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
